[tool.poetry]
name = "add-to-path"
version = "0.1.0"
description = ""
authors = ["Sandenberg Ferreira Melo <sandenbergferreiramelo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyqtdarktheme = "^1.1.0"
PyQt5 = "^5.15.7"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
